# Generated by Django 3.1.2 on 2020-10-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=240)),
                ('certification_code', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
