# Generated by Django 3.1.2 on 2020-10-14 08:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('boxes', '0002_auto_20201014_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='coach',
            field=models.ManyToManyField(blank=True, related_name='box_coaches', to=settings.AUTH_USER_MODEL),
        ),
    ]
