# Generated by Django 3.1.2 on 2020-10-14 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_hasnewalert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='hasNewAlert',
            new_name='has_new_alert',
        ),
    ]
