# Generated by Django 3.1.2 on 2020-10-21 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201014_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_state',
            field=models.CharField(choices=[('unregistered', 'Unregistered'), ('pending', 'Pending'), ('registered', 'Registered')], default='unregistered', max_length=40),
        ),
    ]
