# Generated by Django 3.1.2 on 2020-11-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_registration_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='certification_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
