# Generated by Django 3.1.2 on 2020-12-08 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_certification_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('unselected', 'Unselected')], default='unselected', max_length=10),
        ),
    ]
