# Generated by Django 3.1.2 on 2020-10-14 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boxes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WodSort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Wod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('comment', models.CharField(blank=True, max_length=120)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('rounds', models.IntegerField(blank=True, null=True)),
                ('rest_sec', models.IntegerField(blank=True, null=True)),
                ('round_sec', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField()),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wods', to='boxes.box')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wods', to='wods.wodsort')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
