# Generated by Django 3.1.2 on 2020-10-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0002_membership_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='state',
            field=models.CharField(choices=[('progress', 'Progress'), ('expired', 'Expired')], default='progress', max_length=80),
        ),
    ]
