# Generated by Django 3.1.2 on 2020-12-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_auto_20201016_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='hold_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
