# Generated by Django 3.1.2 on 2020-10-07 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boxes', '0003_auto_20201005_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('alert_type', models.CharField(choices=[('notice', 'Notice'), ('event', 'Event'), ('message', 'Message')], default='notice', max_length=20)),
                ('title', models.CharField(max_length=40)),
                ('content', models.CharField(max_length=120)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='boxes.box')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
