# Generated by Django 3.1.2 on 2020-11-29 06:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_remove_alert_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
